export const ICON_LOADING_CIRCLE = 'svg-spinners:180-ring-with-bg'
export const ICON_HOME = 'mi:home'
export const ICON_EYE_SHOW = 'clarity:eye-show-line'
export const ICON_EYE_HIDE = 'clarity:eye-hide-line'
export const ICON_EMPTY = 'tabler:table-alias'
export const ICON_ERROR = 'tabler:table-down'
